spring.application.name=Ass02_Spring_JBDC_application_Using_Stored_ProcedureORFunction

#DataSource Property

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sb01db
spring.datasource.username=root
spring.datasource.password=root