spring.application.name=Ass08_SEQUENCE_Primary_Key_Generation_Postgresql

#DataSource Property
spring.datasource.url=jdbc:postgresql://localhost:5432/sb01db
spring.datasource.username=root
spring.datasource.password=root@123


#JPA Property
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
