spring.application.name=Ass06_IDENTITY_Primary_Key_Generation

#DataSource Property
spring.datasource.url=jdbc:mysql://localhost:3306/sb01db
spring.datasource.username=root
spring.datasource.password=root


#JPA Property
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
