spring.application.name=Ass14_Custom_ID_Generation_With_Generic_Generator_PostgreSql_MySql

#DataSource Properties
spring.datasource.url=jdbc:mysql://localhost:3306/sb01db
spring.datasource.username=root
spring.datasource.password=root

#JPA Property
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
