#AdminService Configuration file

admin.url="https:/admin.tca.com"
admin.port=8080
admin.user=admin
admin.password=root@123


#Email Config File
#smtp.url="smgtp.gmail.com"
#smtp.port=9090
#to.address="aniket@gmail.com
#from.address="tca@gmail.com"