spring.application.name=Ass16_One_To_Many_Relationship

#DataSource Property
spring.datasource.url=jdbc:mysql://localhost:3306/sb01db
spring.datasource.username=root
spring.datasource.password=root

#Spring Data JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

